baseURL = "/"
languageCode = "en"
defaultContentLanguage = "en"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[params.author]
   name = "Lyyka"
   headline = "A silly dog on the internet"
   image = "author.jpg"  # path relative to static directory

  links = [
     { bluesky = "https://bsky.app/profile/lyykapaws.com" },
     { twitter = "https://twitter.com/LyykaPaws" },
     { twitch = "https://twitch.tv/lyykapaws" },
     { youtube = "https://youtube.com/@lyykapaws" },
     { github = "https://github.com/lyykapaws" },
  ]

[module]
  [module.hugoVersion]
    extended = false
    min = "0.86.1"
[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true