baseurl = "/"
title = 'LyykaPaws'
theme = 'lynx'

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[author]
	name = "LyykaPaws"
	headline = "Just a fluffy dog who wants to make everyone's day a bit happier."
	image = "dog.png"
	links = [
		{ github = "https://github.com/LyykaPaws" },
		{ twitter = "https://twitter.com/LyykaPaws" },
		{ twitch = "https://twitch.tv/lyykapaws" },
		{ youtube = "https://youtube.com/@lyykapaws" },
		{ discord = "https://discord.gg/tVyqBbT" },
		{ telegram = "https://t.me/lyykasden" },
	]


[markup.highlight]
	noClasses = false

[markup.goldmark]
[markup.goldmark.renderer]
	unsafe = true